package azure

import (
	"context"
	"strings"

	"github.com/Azure/azure-sdk-for-go/profiles/latest/cdn/mgmt/cdn"
	"github.com/turbot/steampipe-plugin-sdk/v5/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin/transform"
)

func tableAzureCDNFrontDoorEndpoint(_ context.Context) *plugin.Table {
	return &plugin.Table{
		Name:        "azure_cdn_frontdoor_endpoint",
		Description: "Azure CDN Front Door Endpoint",
		Get: &plugin.GetConfig{
			KeyColumns: plugin.AllColumns([]string{"name", "profile_name", "resource_group"}),
			Hydrate:    getAzureCDNFrontDoorEndpoint,
			Tags: map[string]string{
				"service": "Microsoft.Cdn",
				"action":  "afdEndpoints/read",
			},
			IgnoreConfig: &plugin.IgnoreConfig{
				ShouldIgnoreErrorFunc: isNotFoundError([]string{"ResourceNotFound", "ResourceGroupNotFound", "404"}),
			},
		},
		List: &plugin.ListConfig{
			ParentHydrate: listAzureCDNFrontDoorProfiles,
			Hydrate:       listAzureCDNFrontDoorEndpoints,
			Tags: map[string]string{
				"service": "Microsoft.Cdn",
				"action":  "afdEndpoints/read",
			},
			KeyColumns: plugin.KeyColumnSlice{
				{Name: "profile_name", Require: plugin.Optional, Operators: []string{"="}},
				{Name: "resource_group", Require: plugin.Optional, Operators: []string{"="}},
				{Name: "name", Require: plugin.Optional, Operators: []string{"=", "<>"}},
			},
		},
		Columns: azureColumns([]*plugin.Column{
			{
				Name:        "name",
				Description: "The name of the endpoint.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Name"),
			},
			{
				Name:        "id",
				Description: "The resource identifier.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromGo(),
			},
			{
				Name:        "profile_name",
				Description: "The name of the Front Door profile.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("AFDEndpointProperties.ProfileName"),
			},
			{
				Name:        "type",
				Description: "The resource type.",
				Type:        proto.ColumnType_STRING,
			},
			{
				Name:        "location",
				Description: "The location of the endpoint.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Location").Transform(toLower),
			},
			{
				Name:        "host_name",
				Description: "The hostname of the endpoint.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("AFDEndpointProperties.HostName"),
			},
			{
				Name:        "enabled_state",
				Description: "Whether the endpoint is enabled.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("AFDEndpointProperties.EnabledState"),
			},
			{
				Name:        "provisioning_state",
				Description: "Provisioning status of the endpoint.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("AFDEndpointProperties.ProvisioningState"),
			},
			{
				Name:        "deployment_status",
				Description: "Deployment status of the endpoint.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("AFDEndpointProperties.DeploymentStatus"),
			},
			{
				Name:        "auto_generated_domain_name_label_scope",
				Description: "Indicates the endpoint name reuse scope.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("AFDEndpointProperties.AutoGeneratedDomainNameLabelScope"),
			},
			{
				Name:        "system_data",
				Description: "Azure system metadata for the endpoint.",
				Type:        proto.ColumnType_JSON,
			},

			// Steampipe standard columns
			{
				Name:        "title",
				Description: ColumnDescriptionTitle,
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Name"),
			},
			{
				Name:        "tags",
				Description: ColumnDescriptionTags,
				Type:        proto.ColumnType_JSON,
			},
			{
				Name:        "akas",
				Description: ColumnDescriptionAkas,
				Type:        proto.ColumnType_JSON,
				Transform:   transform.FromField("ID").Transform(idToAkas),
			},

			// Azure standard columns
			{
				Name:        "region",
				Description: ColumnDescriptionRegion,
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Location").Transform(toLower),
			},
			{
				Name:        "resource_group",
				Description: ColumnDescriptionResourceGroup,
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("ID").Transform(extractResourceGroupFromID),
			},
		}),
	}
}

func listAzureCDNFrontDoorEndpoints(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
	profile := h.Item.(cdn.Profile)
	profileName := *profile.Name
	resourceGroup := strings.Split(*profile.ID, "/")[4]

	if qual := d.EqualsQualString("profile_name"); qual != "" && qual != profileName {
		return nil, nil
	}
	if qual := d.EqualsQualString("resource_group"); qual != "" && qual != resourceGroup {
		return nil, nil
	}

	session, err := GetNewSession(ctx, d, "MANAGEMENT")
	if err != nil {
		plugin.Logger(ctx).Error("azure_cdn_frontdoor_endpoint.listAzureCDNFrontDoorEndpoints", "session_error", err)
		return nil, err
	}

	client := cdn.NewAFDEndpointsClientWithBaseURI(session.ResourceManagerEndpoint, session.SubscriptionID)
	client.Authorizer = session.Authorizer

	ApplyRetryRules(ctx, &client, d.Connection)

	result, err := client.ListByProfile(ctx, resourceGroup, profileName)
	if err != nil {
		plugin.Logger(ctx).Error("azure_cdn_frontdoor_endpoint.listAzureCDNFrontDoorEndpoints", "api_error", err)
		return nil, err
	}

	for _, endpoint := range result.Values() {
		if shouldIgnoreFrontDoorEndpointByName(d, endpoint) {
			continue
		}
		d.StreamListItem(ctx, endpoint)
		if d.RowsRemaining(ctx) == 0 {
			return nil, nil
		}
	}

	for result.NotDone() {
		d.WaitForListRateLimit(ctx)

		err = result.NextWithContext(ctx)
		if err != nil {
			plugin.Logger(ctx).Error("azure_cdn_frontdoor_endpoint.listAzureCDNFrontDoorEndpoints", "paging_error", err)
			return nil, err
		}
		for _, endpoint := range result.Values() {
			if shouldIgnoreFrontDoorEndpointByName(d, endpoint) {
				continue
			}
			d.StreamListItem(ctx, endpoint)
			if d.RowsRemaining(ctx) == 0 {
				return nil, nil
			}
		}
	}

	return nil, nil
}

func getAzureCDNFrontDoorEndpoint(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
	name := d.EqualsQuals["name"].GetStringValue()
	profileName := d.EqualsQuals["profile_name"].GetStringValue()
	resourceGroup := d.EqualsQuals["resource_group"].GetStringValue()

	if name == "" || profileName == "" || resourceGroup == "" {
		return nil, nil
	}

	session, err := GetNewSession(ctx, d, "MANAGEMENT")
	if err != nil {
		plugin.Logger(ctx).Error("azure_cdn_frontdoor_endpoint.getAzureCDNFrontDoorEndpoint", "session_error", err)
		return nil, err
	}

	client := cdn.NewAFDEndpointsClientWithBaseURI(session.ResourceManagerEndpoint, session.SubscriptionID)
	client.Authorizer = session.Authorizer

	ApplyRetryRules(ctx, &client, d.Connection)

	endpoint, err := client.Get(ctx, resourceGroup, profileName, name)
	if err != nil {
		plugin.Logger(ctx).Error("azure_cdn_frontdoor_endpoint.getAzureCDNFrontDoorEndpoint", "api_error", err)
		return nil, err
	}

	if endpoint.ID != nil {
		return endpoint, nil
	}

	return nil, nil
}

func shouldIgnoreFrontDoorEndpointByName(d *plugin.QueryData, endpoint cdn.AFDEndpoint) bool {
	if d.Quals["name"] == nil {
		return false
	}

	name := ""
	if endpoint.Name != nil {
		name = *endpoint.Name
	}

	for _, q := range d.Quals["name"].Quals {
		switch q.Operator {
		case "=":
			if name != q.Value.GetStringValue() {
				return true
			}
		case "<>":
			if name == q.Value.GetStringValue() {
				return true
			}
		}
	}

	return false
}
